/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

import edu.curso.view.ToDoListUI;
import javafx.application.Application;

public class App {
    public static void main(String[] args) {
        Application.launch(ToDoListUI.class, args);
    }
}
